services:
  - type: web
    name: document-paddleocr-service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PADDLEOCR_LANG
        value: ch
      - key: MAX_PDF_PAGES
        value: "8"
