services:
  - type: web
    name: document-paddleocr-service
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: MAX_PDF_PAGES
        value: "8"
      - key: MAX_IMAGE_SIDE
        value: "1500"
      - key: OCR_ENGINE
        value: tesseract
